// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mewxlbirptltrdqxidlb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ld3hsYmlycHRsdHJkcXhpZGxiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MDE5NjcsImV4cCI6MjA3MDk3Nzk2N30.oYUSzWo11So311vBh1irz-gxFq1Rz26iUjBXlDdKimA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});